DROP DATABASE IF EXISTS PQRS;
CREATE DATABASE IF NOT EXISTS PQRS;

-- Tabla Instancia;

DROP TABLE IF EXISTS PQRS.INSTANCIA;

CREATE TABLE IF NOT EXISTS PQRS.INSTANCIA (
    ID_INSTANCIA INT(10) NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    URL_ICON VARCHAR(500) NOT NULL,
    URL_LOGO VARCHAR(500) NOT NULL,
    PRIMARY KEY (ID_INSTANCIA)
) ENGINE = InnoDB DEFAULT CHARSET = UTF8;

-- Tabla Sucursal;

DROP TABLE IF EXISTS PQRS.SUCURSAL;

CREATE TABLE IF NOT EXISTS PQRS.SUCURSAL (
    ID_SUCURSAL INT(10) NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    ID_INSTANCIA INT(10) NOT NULL,
    PRIMARY KEY (ID_SUCURSAL),
    FOREIGN KEY (ID_INSTANCIA) REFERENCES INSTANCIA(ID_INSTANCIA) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = UTF8;

-- Tabla Usuario

DROP TABLE IF EXISTS PQRS.USUARIO;

CREATE TABLE IF NOT EXISTS PQRS.USUARIO (
    ID_USUARIO INT(10) NOT NULL AUTO_INCREMENT,
    NOMBRES VARCHAR(100) NOT NULL,
    APELLIDOS VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    TELEFONO INTEGER NOT NULL,
    EXT INTEGER NOT NULL,
    TIPO_USUARIO VARCHAR(20) NOT NULL,
    PASSWORD VARCHAR(60) NOT NULL,
    ID_SUCURSAL INT(10),
    PRIMARY KEY (ID_USUARIO),
    FOREIGN KEY (ID_SUCURSAL) REFERENCES SUCURSAL(ID_SUCURSAL) ON DELETE CASCADE,
    CONSTRAINT email_unique UNIQUE (EMAIL)
) ENGINE = InnoDB DEFAULT CHARSET = UTF8;

-- Tabla Proveedor

DROP TABLE IF EXISTS PQRS.PROVEEDOR;

CREATE TABLE IF NOT EXISTS PQRS.PROVEEDOR (
    ID_PROVEEDOR INT(10) NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID_PROVEEDOR)
) ENGINE = InnoDB DEFAULT CHARSET = UTF8;

-- Tabla Producto

DROP TABLE IF EXISTS PQRS.PRODUCTO;

CREATE TABLE IF NOT EXISTS PQRS.PRODUCTO (
    ID_PRODUCTO INT(10) NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID_PRODUCTO)
) ENGINE = InnoDB DEFAULT CHARSET = UTF8;

-- Tabla Tipo de Solicitud

DROP TABLE IF EXISTS PQRS.TIPO_SOLICITUD;

CREATE TABLE IF NOT EXISTS PQRS.TIPO_SOLICITUD (
    ID_TIPO_SOLICITUD INT(10) NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID_TIPO_SOLICITUD)
) ENGINE = InnoDB DEFAULT CHARSET = UTF8;

-- Tabla Causas

DROP TABLE IF EXISTS PQRS.CAUSA;

CREATE TABLE IF NOT EXISTS PQRS.CAUSA (
    ID_CAUSA INT(10) NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID_CAUSA)
) ENGINE = InnoDB DEFAULT CHARSET = UTF8;

-- Tabla Solicitud

DROP TABLE IF EXISTS PQRS.SOLICITUD;

CREATE TABLE IF NOT EXISTS PQRS.SOLICITUD (
    ID_SOLICITUD INT(10) NOT NULL AUTO_INCREMENT,
    RADICADO INTEGER NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    CEDULA VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    TELEFONO VARCHAR(15),
    RESERVA VARCHAR(20),
    ESTADO VARCHAR(20),
    FECHA DATE,
    DESCRIPCION VARCHAR(500),
    ID_PRODUCTO INT(10) NOT NULL,
    ID_TIPO_SOLICITUD INT(10) NOT NULL,
    ID_CAUSA INT(10) NOT NULL,
    ID_SUCURSAL INT(10) NOT NULL,
    ID_USUARIO INT(10) NOT NULL,
    ID_SOLICITUD_RESPONDE INT(10),
    ID_PROVEEDOR INT(10),
    PRIMARY KEY (ID_SOLICITUD),
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO) ON DELETE CASCADE,
    FOREIGN KEY (ID_TIPO_SOLICITUD) REFERENCES TIPO_SOLICITUD(ID_TIPO_SOLICITUD) ON DELETE CASCADE,
    FOREIGN KEY (ID_CAUSA) REFERENCES CAUSA(ID_CAUSA) ON DELETE CASCADE,
    FOREIGN KEY (ID_SUCURSAL) REFERENCES SUCURSAL(ID_SUCURSAL) ON DELETE CASCADE,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE,
    FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR(ID_PROVEEDOR) ON DELETE CASCADE,
    FOREIGN KEY (ID_SOLICITUD_RESPONDE) REFERENCES SOLICITUD(ID_SOLICITUD) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = UTF8;

-- Tabla Adjuntos

DROP TABLE IF EXISTS PQRS.ADJUNTO;

CREATE TABLE IF NOT EXISTS PQRS.ADJUNTO (
    ID_ADJUNTO INT(10) NOT NULL AUTO_INCREMENT,
    URL VARCHAR(100) NOT NULL,
    ID_SOLICITUD INT(10) NOT NULL,
    PRIMARY KEY (ID_ADJUNTO),
    FOREIGN KEY (ID_SOLICITUD) REFERENCES SOLICITUD(ID_SOLICITUD) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = UTF8;

-- Tabla Respuesta

DROP TABLE IF EXISTS PQRS.RESPUESTA;

CREATE TABLE IF NOT EXISTS PQRS.RESPUESTA (
    ID_RESPUESTA INT(10) NOT NULL AUTO_INCREMENT,
    URL VARCHAR(100) NOT NULL,
    ID_SOLICITUD INT(10) NOT NULL,
    PRIMARY KEY (ID_RESPUESTA),
    FOREIGN KEY (ID_SOLICITUD) REFERENCES SOLICITUD(ID_SOLICITUD) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = UTF8;
